[project]
name = "AppBasics"
version = "v0.0.0"
authors = [
    { name = "Takanori Kono", email = "takanori.kono@gmail.com" }
]
description = "Basic tools for developing applications"
readme = "README.md"
dependencies = [
    "dotenv",
    "typer",
    "sqlmodel",
    "uvicorn",
    "fire",
    "build",
    "import-linter",
    "twine"
]
[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project.scripts]
apb-managedb = "appbasics.cli.managedb:main"
apb-inspect = "appbasics.cli.inspect:main"
dbapp-run = "appbasics.cli.dbappRun:main"
apb-server-run = "appbasics.cli.serverApp:main"

[tool.hatch.build.targets.wheel]
packages = [ "src/appbasics" ]

[tool.pytest.ini_options]
testpaths = [ "tests" ]
pythonpath = [ "src" ]
filterwarnings = [ "ignore::deprecationWarning" ]
